name: onze_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dot_curved_bottom_nav: ^0.0.2
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  animated_bottom_navigation_bar: ^1.3.3
  moyasar: ^2.0.13
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0
  get_storage: ^2.1.1
  get_it: ^8.0.0
  sizer: ^2.0.15
  pinput: ^5.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env