name: onze_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  moyasar: ^2.0.13
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0
  get_storage: ^2.1.1
  get_it: ^8.0.0
  sizer: ^2.0.15
  pinput: ^5.0.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  onesignal_flutter: ^5.2.5
  http: ^1.2.2
  icons_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env